### ISSUE TITLE
Uploaded GIF files lose their animation

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#173]
Uploaded via Takahe: https://mws.bka.li/takahe/attachments/2022/12/15/1mtymoknw-6_rSdQNEAW4m4zCxs.webp
Original GIF: https://mws.bka.li/sharex/2022/12/347235-Sleep-Well.gif

**Comment by shuuji3** [comment]
I recently learned WebP format also supports the animated image too. Maybe we can use WebP at least for GIF since probably it's relatively easier than implementing video conversion.

Pillow also supports conversion from animated GIF to animated WebP by specifying the specific flag `save_all=True` (ref. [Image file formats - Pillow (PIL Fork) 9.4.0 documentation](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#saving-sequences)).

Safari hasn't supported WebP for a long time but they finally added its support just 4 months ago: https://caniuse.com/webp

**Comment by TkTech** [comment]
I had an experimental change that does video (including gif and apng) conversion, but @andrewgodwin wanted to avoid it for now. I believe there are concerns because we don't have real background workers and the memory overhead.

**Comment by andrewgodwin** [comment]
Yeah, I want to think about this more. I will rename this ticket to represent the feature of "uploading videos" though, as that is the correct way to treat GIFs.

**Comment by andrewgodwin** [comment]
(though I may go shove `save_all=True` in the webp saver for now just to make some GIFs work)

**Comment by andrewgodwin** [comment]
Going to close this in favour of the more general https://github.com/jointakahe/takahe/issues/378

**Comment by shuuji3** [comment]
> (I don't know if save_all will work here because the resize pass will drop the other frames anyway?)

You're right. Before saving as animated WebP, resizing needs to apply to each GIF frame.

Another option is using `gif2webp`: https://developers.google.com/speed/webp/docs/gif2webp
