### ISSUE TITLE
Content Warning/Content Summary name toggle

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#28]
<img width="472" alt="Screen Shot 2022-11-20 at 5 31 57 PM" src="https://user-images.githubusercontent.com/2731744/202929873-7c4050dc-75f7-43c0-bee6-dd66a44f6f16.png">

If an admin can call "Content Warning" something like "Subject Line" or "Summary" et cetera, an admin might be able to sidestep a lengthy discussions about the word "warning".

**Comment by andrewgodwin** [comment]
Yes, I think that's fair - I'd say a server config option that changes it to be "Content Summary" would be good?

**Comment by manfre** [comment]
[I have a branch](https://github.com/manfre/takahe/commit/6fb0e07ef5323de6e11581f45a048e21f3a36e6a) that controls the label and placeholder with a config. Didn't open a PR yet because had to step away from computer before adding tests. Is free form control too much? Would you prefer a bool to toggle between "Content Warning" or "Content Summary"?

**Comment by whatSocks** [comment]
Freeform control seems to me to be the best, with the default being "Content Summary". 
Like if my users are too verbose having tl;dr might be the best

**Comment by andrewgodwin** [comment]
Let's go freeform control with "Content Summary" as the default. We can switch the "CW" button that's on the mini-compose right now to an icon.

**Comment by andrewgodwin** [comment]
Actually, changed my mind - I think "Content Warning" is a better default as that is the name people expect from Mastodon and general use.
