### ISSUE TITLE
Will oauth with grant_type='password' be supported in the future

### ISSUE THREAD

**Issue by marvin8** [jointakahe/takahe#455]
In a couple of small [mastodon tools I've written](https://codeberg.org/MarvinsMastodonTools) I've been using grant_type = 'password' to create an access_token on the first run to configure which mastodon account to work with.

It looks like at this time Takahe does not support authentication with  grant_type='password'.  Is this something that is planned or just likely to be supported in the future? 

Eitherway, Takahe looks like an awesome project. Thanks all for sharing your tremendous work.

**Comment by andrewgodwin** [comment]
We can't support it at this point because we need to show the identity select screen - unlike Mastodon, a username and password alone is not enough to resolve exactly what account you want to give access to.

Given that and the security issues with it, I don't think we plan to support it unless a very compelling reason turns up? I know it makes CLI tools more annoying to write, but we do support the "return me a code to type in" flow just in case *that* is needed.

**Comment by marvin8** [comment]
Thanks for the quick response. I kind of expected what you said... I'll guess I'll rewrite my tools first run code at some point.

I'll close this issue know.
