### ISSUE TITLE
Unable to favourite any posts

### ISSUE THREAD

**Issue by chris-y** [jointakahe/takahe#599]
I can't favourite anything on Takahē.social. On the web interface it just ignores me, on an app it appears to favourite but refreshing shows the star still unhighlighted.

**Comment by chris-y** [comment]
It doesn't work from the mentions view in Tusky, but if I expand a conversation and favourite there it does. Going back to the mentions view it still shows as not favourited, going into the thread it is highlighted! Very strange.

![Screenshot_20230705-074156-619.png](https://github.com/jointakahe/takahe/assets/1818803/5f004555-5530-4895-8ab1-6ba107b8998e)

![Screenshot_20230705-074212-882.png](https://github.com/jointakahe/takahe/assets/1818803/004cc631-3ef6-45b0-ba35-9b59b2395cbe)

**Comment by andrewgodwin** [comment]
Well the Takahē web interface no longer has a favourite option - all it'll do is show the number of favourites, so I'm not sure what you're seeing there.

For the Tusky scenario, it looks like it's because we don't include the interaction metadata on the notifications API endpoint. I'll see if I can fix that.
